### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by borismattijssen** [borismattijssen/spark-flights#1]
Visualization:

- [ ] Date(time) vs delaytime

Other:

- [ ] Study influence of flight number on the delay time
- [ ] Engineer new features (e.g. airport_cancellation, is_holiday, some aggregate)
- [ ] Encode categorical features
- [ ] Create new features out of hhmm encoded features
- [ ] Decide on a regression model
- [ ] See what canceled flights look like (do they have delay time?)
